### PR TITLE
Comply with REUSE version 3.0 for licensing declaration.

### PR DESCRIPTION
**Pull request by apteryks**
This change also standardizes the line endings in the HTML files to use LF (Unix); these were mixed.

### CODE REVIEW

**Review by arthurgleckler — CHANGES_REQUESTED** [review]
There are lots of extraneous changes in this pull request.  I'm guessing that it's changes in ^M line endings.  I've ignored smaller numbers of them in order pull requests, but it would be best not to change those.  Would you please undo those?

Thanks.

**Comment by apteryks** [comment]
Hi Arthur!

I think the `reuse` tool was having problems with mixed line endings hence why I "also standardized the line endings in the HTML files to
use LF (Unix)" in the commit.

I think it's undesirable that these were mixed in the first place, but I agree it'd be nicer if extract in a first (prelude) commit.  Would that be agreeable to you?

Thanks for the reviews and merge so far!

**Comment by arthurgleckler** [comment]
That would be great.  Thank you!

**Comment by apteryks** [comment]
> That would be great. Thank you!

Done, at last.

**Comment by arthurgleckler** [comment]
Thanks.  Reviewed, merged, and pushed.

**Pull request merged**
